### ISSUE TITLE
Unable to run without error

### ISSUE THREAD

**Issue by Litleck** [BlueManCZ/SIF#18]
I am on Ubuntu 20.04, with Python 3.8.5. I've made sure to install everything but when I run the python file I just get an error. At first, it will work fine and ask me to terminate steam but then that's when it messes up.

```
Creating .desktop files in /home/litleck/.local/share/applications/steam-icons-fixed

Traceback (most recent call last):
  File "./sif.py", line 492, in <module>
    fix_launch_option(game, game_wm_name, game_wm_name_alt)
  File "./sif.py", line 157, in fix_launch_option
    apps = loaded['UserLocalConfigStore']['Software']['Valve']['Steam']['Apps']
KeyError: 'Apps'
```

I have no clue what this means but I was hoping maybe I could get help here.

**Comment by BlueManCZ** [comment]
Hello @Litleck! Never seen this error before. Can you please run the script with `--verbose` flag and post the output here?

**Comment by Litleck** [comment]
> Hello @Litleck! Never seen this error before. Can you please run the script with `--verbose` flag and post the output here?

Here you go
```Working with Papirus-Dark icon theme.

[ok] Found Steam installation directory:
   - /home/litleck/.steam/steam

[ok] Found Steam configuration file:
   - /home/litleck/.steam/steam/config/config.vdf

[ok] Found Steam library folders:
   - /home/litleck/.steam/steam/steamapps

[ok] Found Steam localconfig.vdf file:
   - /home/litleck/.steam/steam/userdata/159469981/config/localconfig.vdf

[ok] Found wm-class-database file:
   - /home/litleck/Downloads/SIF/wm-class-database.json

[ok] Found target directory:
   - /home/litleck/.local/share/applications/steam-icons-fixed

Creating .desktop files in /home/litleck/.local/share/applications/steam-icons-fixed

Traceback (most recent call last):
  File "./sif.py", line 492, in <module>
    fix_launch_option(game, game_wm_name, game_wm_name_alt)
  File "./sif.py", line 157, in fix_launch_option
    apps = loaded['UserLocalConfigStore']['Software']['Valve']['Steam']['Apps']
KeyError: 'Apps'
```

**Comment by BlueManCZ** [comment]
This is strange. Can you post content of your `/home/litleck/.steam/steam/userdata/159469981/config/localconfig.vdf` file? For example on https://pastebin.com/. It is the file that causes this problem. Inside should be JSON structure looking like this:
```
"UserLocalConfigStore"
{
	"Software"
	{
		"Valve"
		{
			"Steam"
			{
				"Apps"
				{
```
And for some reason, your "Apps" key is missing.

**Comment by BlueManCZ** [comment]
By the way, when script asks you to terminate Steam and you answer No, it should run fine. Am I right?

**Comment by Litleck** [comment]
> This is strange. Can you post content of your `/home/litleck/.steam/steam/userdata/159469981/config/localconfig.vdf` file? For example on [pastebin.com](https://pastebin.com/). It is the file that causes this problem. Inside should be JSON structure looking like this:
> 
> ```
> "UserLocalConfigStore"
> {
> 	"Software"
> 	{
> 		"Valve"
> 		{
> 			"Steam"
> 			{
> 				"Apps"
> 				{
> ```
> 
> And for some reason, your "Apps" key is missing.

https://pastebin.com/vjcqhHCB

> By the way, when script asks you to terminate Steam and you answer No, it should run fine. Am I right?

Yes, it says that `Some games couldn't be fixed due to running Steam`

**Comment by BlueManCZ** [comment]
Pastebin says it's no longer available. Can you try it again?

**Comment by BlueManCZ** [comment]
Just to make sure, this command `find /home/ivo/.steam/steam/userdata/ | grep localconfig.vdf` returns only one file, right?

**Comment by Litleck** [comment]
My bad, here's the Pastebin again [https://pastebin.com/DGQcN6U2](url)
And that command does return only one file.
`/home/litleck/.steam/steam/userdata/159469981/config/localconfig.vdf`

**Comment by BlueManCZ** [comment]
It still doesn't work. Does it work for you in an anonymous window? You can try https://dpaste.com/

**Comment by Litleck** [comment]
> It still doesn't work. Does it work for you in an anonymous window? You can try [dpaste.com](https://dpaste.com/)

https://dpaste.com/A8VVSVTCN
Hopefully this one works

**Comment by Litleck** [comment]
It seems like it has some limit to the content size

**Comment by BlueManCZ** [comment]
Is that file cut on line 115 in your system too?

**Comment by Litleck** [comment]
Yes

**Comment by BlueManCZ** [comment]
It is not dpaste related?

**Comment by Litleck** [comment]
In the preview on dpaste it shows all the content in there but on the actual link its cut off at that line.

**Comment by BlueManCZ** [comment]
Great! I see a problem. Your file uses "apps" as a key instead of "Apps" for some reason. I will try to fix this in the script and let you know.

**Comment by BlueManCZ** [comment]
Does it work for you know, when you update with `git pull`?

**Comment by Litleck** [comment]
> Does it work for you now, when you update with `git pull`?

That seems to have fixed it.
Thank you.
