### ISSUE TITLE
Support for Europa Universalis IV

### ISSUE THREAD

**Issue by frederikpyt** [BlueManCZ/SIF#20]
Appid: "236850"
WM_CLASS: "eu4", "paradox launcher"

Icon from papirus: "/home/user/.local/share/icons/Papirus/48x48/categories/steam_icon_236850.svg"

Edit:
Added launcher WM_CLASS also in case you need it. Beware that the other paradox games use the same launcher

**Comment by BlueManCZ** [comment]
Thank you for your input!

> Added launcher WM_CLASS also in case you need it. Beware that the other paradox games use the same launcher

I can't easily fix icon of the launcher, because of this common WM_CLASS, as you said. I don't know which icon to use for it.
