### ISSUE TITLE
[Database Request] Factorio

### ISSUE THREAD

**Issue by Kaperios** [BlueManCZ/SIF#3]
**APP_ID:** 427520
**WM_CLASS:** factorio
**Icon Theme:** Papirus-Dark

**Comment by BlueManCZ** [comment]
Can you confirm this and #4 work now? Thank you. :octocat:

**Comment by Kaperios** [comment]
It does indeed work. I hope the spam won't bother you that much :P

**Comment by BlueManCZ** [comment]
> It does indeed work.

Great!

> I hope the spam won't bother you that much :P

Nah, provide everything you can. Who cares about spam. :smile:
