### ISSUE TITLE
Icon request: kotor 2

### ISSUE THREAD

**Issue by tamsyn548** [BlueManCZ/SIF#30]
APP_ID: 208580
WM_CLASS: "KOTOR2", "KOTOR2"
Icon Theme: Numix (Square)

**Comment by BlueManCZ** [comment]
Hi, thank you for the initiative. I added the icon. Let me know if it works. :octocat:

**Comment by tamsyn548** [comment]
you are amazing! it works perfectly!!

I also made a request for another game just now :))

**Comment by BlueManCZ** [comment]
Great! Added it too. Does it work? :eyes:

**Comment by tamsyn548** [comment]
> Great! Added it too. Does it work? eyes

yes sir! You just made my day. this issue used to cause me endless frustration

**Comment by BlueManCZ** [comment]
I'm glad I could help. Frustration was the main reason I wrote this tool. Feel free to open new icon requests anytime.
