### ISSUE TITLE
Icon Request: Stardew Valley w/ SMAPI

### ISSUE THREAD

**Issue by tamsyn548** [BlueManCZ/SIF#33]
APP_ID: 413150
WM_CLASS: "StardewModdingAPI", "StardewModdingAPI"
Icon Pack: Numix Square

I want it to just have the same icon as the base, unmodded Stardew Valley game.

**Comment by BlueManCZ** [comment]
Added. Does it work as expected?

**Comment by tamsyn548** [comment]
> Added. Does it work as expected?

it does! I'm so happy

**Comment by tamsyn548** [comment]
![Screenshot from 2023-01-21 11-42-23](https://user-images.githubusercontent.com/111175305/213882302-ba1711fd-37a1-43c2-9548-3978e8a267c2.png)

**Comment by BlueManCZ** [comment]
Nice
