### ISSUE TITLE
Icon Request: Darkest Dungeon

### ISSUE THREAD

**Issue by tamsyn548** [BlueManCZ/SIF#34]
APP_ID: 262060
WM_CLASS: "darkest.bin.x86_64"
Icon Pack: Numix Square

**Comment by BlueManCZ** [comment]
Hi, this is already present in the database: https://github.com/BlueManCZ/SIF/blob/6874d8b4c9d3e0162dc65fb99d6349cbc1c707f3/database.json#L34
It should start working as soon as somebody creates the Numix icon. You can create Icon Request here: https://github.com/numixproject/numix-core/issues
